import type { Metadata } from "next";
import "../globals.css";
import React from "react";
import Navbar from "@/components/Topbar";
import SmallScreenNavBar from "@/components/Topbar/SmallScreenNavBar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function HomeLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div>
      {/* navbar for large screen */}
      <Navbar />
      <SmallScreenNavBar>{children}</SmallScreenNavBar>
    </div>
  );
}
