import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import React from "react";
import GlobalModal from "@/components/Modals/GlobalModal";
import ReduxStoreProvider from "@/components/HOC/ReduxStoreProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={inter.className} style={{ overflow: "hidden" }}>
          <ReduxStoreProvider>
            <main>
              <GlobalModal />
              {children}
            </main>
          </ReduxStoreProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
